image: node

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - npm install
    - npm run build
    - echo "Compile complete."
# unit-test-job:
#   stage: test
#   script:
#     - echo "Running unit tests..."
#     - npm install
#     - npm run test
